### ISSUE TITLE
Feature request: other type of keys?

### ISSUE THREAD

**Issue by sudodoki** [jlahd/cacle#1]
Hello! Loving the idea behind your project. One other extension point I'm seeing that would benefit the users, possibly, is the ability to use other things as keys, not only numbers. Thoughts? Personally, I found this project while searching for thread safe lru cache for my needs of storing some strings and objects.

**Comment by jlahd** [comment]
Hello!
Thanks for the feedback! As a key, you can use anything you can use as a key on a hashtable. By default, the test function is `eql`, tough - so if you use strings, be sure to include `:test 'equal` in the arguments to `make-cache`.

**Comment by sudodoki** [comment]
Maybe, I'm doing something wrong though.
```
(defun test-provider (key)
    (values (format nil "~a" key) key))
(defparameter *my-cache* (cacle:make-cache 100 #'test-provider :policy :lru :test 'equal))
(cacle:cache-fetch *my-cache* "some string")
```
I get
```
The value
  "some string"
is not of type
  NUMBER
when binding SB-KERNEL::X

  0: (SB-KERNEL:TWO-ARG-+ "some string" 0) [external]
  1: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN CACLE:CACHE-FETCH))
  2: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
  3: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN CACLE:CACHE-FETCH) {924CBFB}> #<SB-THREAD:MUTEX "cache" owner: #<SB-THREAD:THREAD "repl-thread" RUNNING {10144F8003}>> NIL T..
```

And if I would run it once again
```
(cacle:cache-fetch *my-cache* "some string")
```


I would get
```
There is no applicable method for the generic function
  #<STANDARD-GENERIC-FUNCTION CACLE:UNLINK (1)>
when called with arguments
  (#<CACLE:CACHE-ENTRY key "some string" {100925B4D3}>).
   [Condition of type SB-PCL::NO-APPLICABLE-METHOD-ERROR]

((:METHOD NO-APPLICABLE-METHOD (T)) #<STANDARD-GENERIC-FUNCTION CACLE:UNLINK (1)> #<CACLE:CACHE-ENTRY key "some string" {100925B4D3}>) [fast-method]
  1: (SB-PCL::CALL-NO-APPLICABLE-METHOD #<STANDARD-GENERIC-FUNCTION CACLE:UNLINK (1)> (#<CACLE:CACHE-ENTRY key "some string" {100925B4D3}>))
  2: ((:METHOD CACLE:ACCESS-ENTRY (CACLE:LRU-REPLACEMENT-POLICY CACLE:CACHE-ENTRY)) #<CACLE:LRU-REPLACEMENT-POLICY  {100925A213}> #<CACLE:CACHE-ENTRY key "some string" {100925B4D3}>) [fast-method]
```

**Comment by jlahd** [comment]
`test-provider` must return two values: Your actual data for the cache entry, and the size of the entry. You are now returning the key as the size, and as your key is a string, you are saying that your cache entry is `"some-string"` bytes long. That is not quite valid.
Try, for example, the following:
```
    (defun test-provider (key)
      (values key (1+ (random 20))))
    (defparameter *my-cache* (cacle:make-cache 100 #'test-provider :policy :lru :test 'equal))
    (cacle:cache-fetch *my-cache* "some string")
```

**Comment by sudodoki** [comment]
thanks! I won't lie to you, I don't get the full idea behind this, but I see that I was trying to use this incorrectly

**Comment by jlahd** [comment]
Remember that cacle supports (and, really, is designed for) storing of the actual cached data somewhere else, not only in the memory. This means that your payload data, as returned by the provider function, could be, for example, a pathname, a uri, or a key to a database. Thus, cacle has no means to generically find out what is the size of each cached value; on the other hand, it must keep the total cache size below the maximum specified in the call to `make-cache`, so it must know the size of each value. Ergo, you need to explicitly tell the size as the second return value of the provider function.
See, for example, the toy cdn node code in the documentation.
